import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:tasktitans/core/theme/app_colors.dart';
import 'package:tasktitans/core/widgets/comic_button.dart';
import 'package:tasktitans/core/widgets/comic_text_field.dart';
import 'package:tasktitans/data/models/mission.dart';
import 'package:tasktitans/data/models/profile.dart';
import 'package:tasktitans/data/repositories/mission_repository.dart';
import 'package:tasktitans/features/auth/application/profile_list_provider.dart';
import 'package:tasktitans/features/auth/application/user_notifier.dart';
import 'package:tasktitans/features/missions/application/mission_list_provider.dart';

class CreateMissionDialog extends ConsumerStatefulWidget {
  final Mission? mission;
  const CreateMissionDialog({super.key, this.mission});

  @override
  ConsumerState<CreateMissionDialog> createState() =>
      _CreateMissionDialogState();
}

class _CreateMissionDialogState extends ConsumerState<CreateMissionDialog> {
  late final TextEditingController _titleController;
  late MissionDifficulty _selectedDifficulty;
  String? _assignedToId; // null means 'Open'
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.mission?.title);
    _selectedDifficulty = widget.mission?.difficulty ?? MissionDifficulty.easy;
    _assignedToId = widget.mission?.assignedTo;
  }

  @override
  void dispose() {
    _titleController.dispose();
    super.dispose();
  }

  void _handleAction() async {
    final title = _titleController.text.trim();
    if (title.isEmpty) return;

    final user = ref.read(userNotifierProvider);
    if (user == null) return;

    setState(() => _isLoading = true);

    // Calculate rewards based on difficulty
    int xp = 0;
    int gold = 0;
    switch (_selectedDifficulty) {
      case MissionDifficulty.easy:
        xp = 100;
        gold = 10;
        break;
      case MissionDifficulty.medium:
        xp = 250;
        gold = 25;
        break;
      case MissionDifficulty.hard:
        xp = 500;
        gold = 50;
        break;
      case MissionDifficulty.epic:
        xp = 1000;
        gold = 100;
        break;
    }

    try {
      final repo = ref.read(missionRepositoryProvider);

      if (widget.mission != null) {
        // UPDATE
        final updatedMission = Mission(
          id: widget.mission!.id,
          familyId: widget.mission!.familyId,
          title: title,
          difficulty: _selectedDifficulty,
          iconId: widget.mission!.iconId,
          status: widget.mission!.status,
          xpReward: xp,
          goldReward: gold,
          createdBy: widget.mission!.createdBy,
          assignedTo: _assignedToId,
        );
        await repo.updateMission(updatedMission);
      } else {
        // CREATE
        final newMission = Mission(
          id: '', // Generated by DB
          familyId: user.familyId,
          title: title,
          difficulty: _selectedDifficulty,
          iconId: 'default', // Placeholder
          status: MissionStatus.available,
          xpReward: xp,
          goldReward: gold,
          createdBy: user.id,
          assignedTo: _assignedToId,
        );
        await repo.createMission(newMission);
      }

      // Refresh list
      ref.invalidate(missionsProvider);

      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.mission != null;
    final profilesAsync = ref.watch(familyProfilesProvider);

    return Dialog(
      backgroundColor: Colors.transparent,
      insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),
      child: Container(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.of(context).size.height * 0.8,
        ),
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(width: 3),
          boxShadow: const [
            BoxShadow(
              color: AppColors.comicBlack,
              offset: Offset(8, 8),
              blurRadius: 0,
            ),
          ],
        ),
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                isEditing ? 'EDIT MISSION' : 'NEW MISSION',
                style: Theme.of(
                  context,
                ).textTheme.titleLarge?.copyWith(fontFamily: 'Bungee'),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 24),
              ComicTextField(
                controller: _titleController,
                label: 'MISSION TITLE',
                hintText: 'e.g. Clean Room',
              ),
              const SizedBox(height: 16),
              const Text(
                'ASSIGN TO',
                style: TextStyle(fontFamily: 'Bungee', fontSize: 14),
              ),
              const SizedBox(height: 8),
              profilesAsync.when(
                data: (profiles) {
                  final children =
                      profiles
                          ?.where((p) => p.role == UserRole.child)
                          .toList() ??
                      [];
                  return Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12),
                    decoration: BoxDecoration(
                      border: Border.all(width: 2),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: DropdownButtonHideUnderline(
                      child: DropdownButton<String?>(
                        value: _assignedToId,
                        isExpanded: true,
                        items: [
                          const DropdownMenuItem(
                            value: null,
                            child: Text(
                              'OPEN TO ALL',
                              style: TextStyle(fontWeight: FontWeight.bold),
                            ),
                          ),
                          ...children.map(
                            (child) => DropdownMenuItem(
                              value: child.id,
                              child: Text(child.username),
                            ),
                          ),
                        ],
                        onChanged:
                            (value) => setState(() => _assignedToId = value),
                      ),
                    ),
                  );
                },
                loading: () => const LinearProgressIndicator(),
                error: (e, s) => const Text('Failed to load titans'),
              ),
              const SizedBox(height: 16),
              const Text(
                'DIFFICULTY',
                style: TextStyle(fontFamily: 'Bungee', fontSize: 14),
              ),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children:
                    MissionDifficulty.values.map((difficulty) {
                      final isSelected = _selectedDifficulty == difficulty;
                      return ChoiceChip(
                        label: Text(
                          difficulty.name.toUpperCase(),
                          style: TextStyle(
                            fontFamily: 'Bungee',
                            color: isSelected ? Colors.white : Colors.black,
                          ),
                        ),
                        selected: isSelected,
                        selectedColor: AppColors.electricBlue,
                        backgroundColor: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                          side: const BorderSide(
                            color: Colors.black,
                            width: 2,
                          ),
                        ),
                        onSelected: (selected) {
                          if (selected) {
                            setState(() => _selectedDifficulty = difficulty);
                          }
                        },
                      );
                    }).toList(),
              ),
              const SizedBox(height: 24),
              ComicButton(
                text:
                    _isLoading
                        ? 'WORKING...'
                        : (isEditing ? 'UPDATE MISSION' : 'PUBLISH MISSION'),
                color: AppColors.hulkGreen,
                onPressed: _isLoading ? null : _handleAction,
              ),
              const SizedBox(height: 12),
              ComicButton(
                text: 'CANCEL',
                color: AppColors.vigilanteRed,
                onPressed: () => context.pop(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
