import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:tasktitans/core/theme/app_colors.dart';
import 'package:tasktitans/core/widgets/comic_button.dart';
import 'package:tasktitans/core/widgets/comic_text_field.dart';
import 'package:tasktitans/data/models/mission.dart';
import 'package:tasktitans/data/repositories/mission_repository.dart';
import 'package:tasktitans/features/auth/application/user_notifier.dart';
import 'package:tasktitans/features/missions/application/mission_list_provider.dart';

class CreateMissionDialog extends ConsumerStatefulWidget {
  const CreateMissionDialog({super.key});

  @override
  ConsumerState<CreateMissionDialog> createState() => _CreateMissionDialogState();
}

class _CreateMissionDialogState extends ConsumerState<CreateMissionDialog> {
  final _titleController = TextEditingController();
  MissionDifficulty _selectedDifficulty = MissionDifficulty.easy;
  bool _isLoading = false;

  void _createMission() async {
    final title = _titleController.text.trim();
    if (title.isEmpty) return;

    final user = ref.read(userNotifierProvider);
    if (user == null) return;

    setState(() => _isLoading = true);

    // Calculate rewards based on difficulty
    int xp = 0;
    int gold = 0;
    switch (_selectedDifficulty) {
      case MissionDifficulty.easy:
        xp = 100;
        gold = 10;
        break;
      case MissionDifficulty.medium:
        xp = 250;
        gold = 25;
        break;
      case MissionDifficulty.hard:
        xp = 500;
        gold = 50;
        break;
      case MissionDifficulty.epic:
        xp = 1000;
        gold = 100;
        break;
    }

    try {
      final mission = Mission(
        id: '', // Generated by DB
        familyId: user.familyId,
        title: title,
        difficulty: _selectedDifficulty,
        iconId: 'default', // Placeholder
        status: MissionStatus.available,
        xpReward: xp,
        goldReward: gold,
        createdBy: user.id,
      );

      await ref.read(missionRepositoryProvider).createMission(mission);
      
      // Refresh list
      ref.invalidate(missionsProvider);
      
      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.transparent,
      child: Container(
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(width: 3),
          boxShadow: const [
            BoxShadow(
              color: AppColors.comicBlack,
              offset: Offset(8, 8),
              blurRadius: 0,
            ),
          ],
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'NEW MISSION',
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontFamily: 'Bungee',
                  ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ComicTextField(
              controller: _titleController,
              label: 'MISSION TITLE',
              hintText: 'e.g. Clean Room',
            ),
            const SizedBox(height: 16),
            const Text(
              'DIFFICULTY',
              style: TextStyle(fontFamily: 'Bungee', fontSize: 14),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: MissionDifficulty.values.map((difficulty) {
                final isSelected = _selectedDifficulty == difficulty;
                return ChoiceChip(
                  label: Text(
                    difficulty.name.toUpperCase(),
                    style: TextStyle(
                      fontFamily: 'Bungee',
                      color: isSelected ? Colors.white : Colors.black,
                    ),
                  ),
                  selected: isSelected,
                  selectedColor: AppColors.electricBlue,
                  backgroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                    side: const BorderSide(color: Colors.black, width: 2),
                  ),
                  onSelected: (selected) {
                    if (selected) setState(() => _selectedDifficulty = difficulty);
                  },
                );
              }).toList(),
            ),
            const SizedBox(height: 24),
            ComicButton(
              text: _isLoading ? 'CREATING...' : 'PUBLISH MISSION',
              color: AppColors.hulkGreen,
              onPressed: _isLoading ? null : _createMission,
            ),
            const SizedBox(height: 12),
            ComicButton(
              text: 'CANCEL',
              color: AppColors.halftoneGrey,
              onPressed: () => context.pop(),
            ),
          ],
        ),
      ),
    );
  }
}
